<?php

namespace App\Imports;

use App\Models\CertificateParticipant;
use App\Models\User;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\SkipsEmptyRows;

class CertificateManualParticipantsImport implements ToCollection, SkipsEmptyRows
{
    protected $certificate;
    protected $errors = [];
    protected $successCount = 0;
    protected $skippedCount = 0;
    protected $createdUserCount = 0;
    protected $processedUserIds = [];

    public function __construct($certificate)
    {
        $this->certificate = $certificate;
    }

    public function collection(Collection $rows)
    {
        if ($rows->isEmpty()) {
            return;
        }

        // Skip header row
        $dataRows = $rows->slice(1);

        foreach ($dataRows as $index => $row) {
            $name = isset($row[0]) ? trim((string) $row[0]) : null;
            $email = isset($row[1]) ? trim((string) $row[1]) : null;
            $phone = isset($row[2]) ? trim((string) $row[2]) : null;

            if (empty($name) && empty($email)) {
                continue;
            }

            $user = null;

            // Prioritas 1: Cocokkan berdasarkan email (paling akurat)
            if (!empty($email)) {
                $user = User::where('email', $email)->first();
            }

            // Prioritas 2: Cocokkan berdasarkan nama + no HP
            if (!$user && !empty($name) && !empty($phone)) {
                $cleanPhone = preg_replace('/[^0-9]/', '', $phone);
                if (str_starts_with($cleanPhone, '0')) {
                    $cleanPhone = substr($cleanPhone, 1);
                } elseif (str_starts_with($cleanPhone, '62')) {
                    $cleanPhone = substr($cleanPhone, 2);
                }

                if (!empty($cleanPhone)) {
                    $user = User::where('name', $name)
                        ->where(function ($q) use ($cleanPhone) {
                            $q->whereRaw("REPLACE(REPLACE(REPLACE(phone_number, ' ', ''), '-', ''), '+', '') = ?", [$cleanPhone])
                              ->orWhereRaw("REPLACE(REPLACE(REPLACE(phone_number, ' ', ''), '-', ''), '+', '') = ?", ['0' . $cleanPhone])
                              ->orWhereRaw("REPLACE(REPLACE(REPLACE(phone_number, ' ', ''), '-', ''), '+', '') = ?", ['62' . $cleanPhone]);
                        })->first();
                }
            }

            // Prioritas 3: Cocokkan berdasarkan nama saja
            if (!$user && !empty($name) && empty($email)) {
                $user = User::where('name', $name)->first();
            }

            // Jika user tidak ditemukan, buat user baru otomatis
            if (!$user) {
                if (empty($email)) {
                    $this->errors[] = "Baris " . ($index + 1) . ": Peserta '{$name}' tidak memiliki email, tidak dapat membuat akun baru.";
                    continue;
                }

                $user = User::create([
                    'name' => $name ?? explode('@', $email)[0],
                    'email' => $email,
                    'phone_number' => $phone,
                    'password' => bcrypt($phone ?? $email),
                ]);

                $user->assignRole('user');
                $this->createdUserCount++;
            }

            // Cek duplikat: user sudah ada di sertifikat ini
            $existingParticipant = CertificateParticipant::where('certificate_id', $this->certificate->id)
                ->where('user_id', $user->id)
                ->exists();

            if ($existingParticipant) {
                $this->skippedCount++;
                continue;
            }

            // Cek duplikat dalam batch import ini
            if (in_array($user->id, $this->processedUserIds)) {
                $this->skippedCount++;
                continue;
            }

            // Buat participant baru (certificate_code & certificate_number auto-generated by model)
            CertificateParticipant::create([
                'certificate_id' => $this->certificate->id,
                'user_id' => $user->id,
            ]);

            $this->processedUserIds[] = $user->id;
            $this->successCount++;
        }
    }

    public function getErrors(): array
    {
        return $this->errors;
    }

    public function getSuccessCount(): int
    {
        return $this->successCount;
    }

    public function getSkippedCount(): int
    {
        return $this->skippedCount;
    }

    public function getCreatedUserCount(): int
    {
        return $this->createdUserCount;
    }
}
